version: "3.7"
services: 
  node-red: 
    build:
      context: ./
      dockerfile: Dockerfile
    image: img-node-red
    container_name: node-red
    environment:
      -TZ=America/Sao_Paulo
    ports:
      - "1880:1880"
    restart: unless-stopped
    volumes:
      - ./data:/data
    networks:
      - node-network

networks:
  node-network:
    driver: bridge   